### PR TITLE
User cannot see premium article in mobile app

### PR DESCRIPTION
**Pull request by ghost**
# [PT Story](https://www.pivotaltracker.com/story/show/172165021)
```
As a user
In order to view the free articles on the application application
I would like to be able be restricted from premium content
```
## Changes proposed in this pull request:
* Adds restriction in specific article
* Added authenticate in root reducers
* Added current user in initial state
## What I have learned working on this feature:
* Adding restriction for user to see premium article in mobile app
* Refreshed knowledge about restriction of content

## Screenshots (Only if client side story)
image

### CODE REVIEW

**Comment by kfrostare** [comment]
Please update the PT-url so it works to click, and double check that the url goes to the correct link. Those are all the notes I have on this :) //Kf

**Comment by ghost** [comment]
> Please update the PT-url so it works to click, and double check that the url goes to the correct link. Those are all the notes I have on this :) //Kf

thanks, done, it was missing a closing hard bracket.

**Comment by kfrostare** [comment]
Looks good to me! /Kf

**Review by hmvitous — APPROVED** [review]
Looks good to me

**Pull request merged**
